const STORE_SECTIONS = 'STORE_SECTIONS';
const STORE_PROJECTS = 'STORE_PROJECTS';
const STORE_SKILLS = 'STORE_SKILLS';
const SWITCH_MODE = 'SWITCH_MODE';
const SWITCH_SECTION = 'SWITCH_SECTION';

export default {
  SWITCH_MODE,
  STORE_SECTIONS,
  STORE_PROJECTS,
  STORE_SKILLS,
  SWITCH_SECTION
}