const STORE_SECTIONS = 'STORE_SECTIONS';
const STORE_PROJECTS = 'STORE_PROJECTS';
const STORE_SKILLS = 'STORE_SKILLS';
const SWITCH_MODE = 'SWITCH_MODE';
const SWITCH_ACTIVE_SECTION = 'SWITCH_ACTIVE_SECTION';
const STORE_QUALIPROJECTS = 'STORE_QUALIPROJECTS';

export default {
  SWITCH_MODE,
  STORE_SECTIONS,
  STORE_PROJECTS,
  STORE_SKILLS,
  STORE_QUALIPROJECTS,
  SWITCH_ACTIVE_SECTION
}