const STORE_SECTIONS = 'STORE_SECTIONS';
const STORE_WORKSECTIONS = 'STORE_WORKSECTIONS';
const STORE_PROJECTS = 'STORE_PROJECTS';
const STORE_SKILLS = 'STORE_SKILLS';
const SWITCH_MODE = 'SWITCH_MODE';
const SWITCH_ACTIVE_SECTION = 'SWITCH_ACTIVE_SECTION';
const STORE_QUALIPROJECTS = 'STORE_QUALIPROJECTS';
const STORE_REFERENCES = 'STORE_REFERENCES';
const STORE_HOME_SCROLL = 'STORE_HOME_SCROLL';
const SWITCH_ACTIVE_WORK = 'SWITCH_ACTIVE_WORK';

export default {
  SWITCH_MODE,
  STORE_SECTIONS,
  STORE_WORKSECTIONS,
  STORE_PROJECTS,
  STORE_SKILLS,
  STORE_QUALIPROJECTS,
  STORE_REFERENCES,
  SWITCH_ACTIVE_SECTION,
  SWITCH_ACTIVE_WORK,
  STORE_HOME_SCROLL
}